---
- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- name: nginx is running
  service:
    name: nginx
    state: started
    enabled: true
